version: '3.9'

services:
  app-database:
    image: postgres
    restart: always
    ports:
      - 5434:5432 # the local machine port is set to 5434 to avoid conflicts with local postgres installation
    environment:
      POSTGRES_PASSWORD: postgres

  app-database-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  app-redis:
    image: redis:7.2
    ports:
      - 6379:6379
