version: '3.9'

services:
  my-db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: postgres

  my-db-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4

  my-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: devenv # this is our dev stage in the Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - my-db # the name of the service
